#!/usr/bin/env python3
"""
Generate simplified ItemDataGenerated.h from item.json
VS2005 compatible - no nullptr, no namespace const
"""

import json
import os

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    json_path = os.path.join(script_dir, '..', 'item.json')
    output_path = os.path.join(script_dir, '..', 'source', 'libs', 'ClientLib', 'src', 'ItemDataGenerated.h')
    
    print(f"Reading: {json_path}")
    with open(json_path, 'r', encoding='utf-8') as f:
        items = json.load(f)
    
    print(f"Loaded {len(items)} items")
    
    # Generate header - VS2005 compatible
    header = '''/**
 * @file ItemDataGenerated.h
 * @brief Auto-generated item data for Pet Filter (VS2005 compatible)
 * 
 * DO NOT EDIT MANUALLY!
 * Generated by: tools/generate_simple_itemdata.py
 * Source: item.json
 */

#ifndef ITEM_DATA_GENERATED_H
#define ITEM_DATA_GENERATED_H

#include <Windows.h>

/* Maximum name lengths */
#define CODENAME_MAX_LEN 64
#define DISPLAYNAME_MAX_LEN 128

/* Simplified item data entry - renamed to avoid conflict with existing SItemData */
typedef struct _PetFilterItemData {
    DWORD refObjID;                     /* Primary key (id) */
    BYTE tid1;                          /* TypeID1 (1=Equipment, 2=Pet, 3=Etc) */
    BYTE tid2;                          /* TypeID2 (sub category) */
    BYTE tid3;                          /* TypeID3 (item type) */
    char codeName[CODENAME_MAX_LEN];    /* Server name (ITEM_CH_SWORD_01_A) */
    char displayName[DISPLAYNAME_MAX_LEN]; /* Display name (Copper Sword) */
} PetFilterItemData;

'''
    
    # Generate item table
    table_lines = []
    table_lines.append(f"/* Total items: {len(items)} */")
    table_lines.append("static const PetFilterItemData g_PetFilterItemTable[] = {")
    
    for item in items:
        item_id = item.get('id', 0)
        tid1 = item.get('tid1', 0)
        tid2 = item.get('tid2', 0)
        tid3 = item.get('tid3', 0)
        code_name = item.get('servername', '')[:63]  # Max 63 chars + null
        display_name = item.get('name', '')[:127]    # Max 127 chars + null
        
        # Escape quotes and backslashes in names
        display_name = display_name.replace('\\', '\\\\').replace('"', '\\"')
        code_name = code_name.replace('\\', '\\\\').replace('"', '\\"')
        
        table_lines.append(f'    {{{item_id}, {tid1}, {tid2}, {tid3}, "{code_name}", "{display_name}"}},')
    
    table_lines.append("};")
    table_lines.append("")
    table_lines.append(f"static const int g_PetFilterItemCount = {len(items)};")
    table_lines.append("")
    table_lines.append("/* Lookup function - VS2005 compatible (no nullptr) */")
    table_lines.append("static const PetFilterItemData* GetPetFilterItemByID(DWORD refObjID) {")
    table_lines.append("    int i;")
    table_lines.append("    for (i = 0; i < g_PetFilterItemCount; i++) {")
    table_lines.append("        if (g_PetFilterItemTable[i].refObjID == refObjID) {")
    table_lines.append("            return &g_PetFilterItemTable[i];")
    table_lines.append("        }")
    table_lines.append("    }")
    table_lines.append("    return NULL;")
    table_lines.append("}")
    table_lines.append("")
    table_lines.append("#endif /* ITEM_DATA_GENERATED_H */")
    table_lines.append("")
    
    # Write output
    print(f"Writing: {output_path}")
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(header)
        f.write('\n'.join(table_lines))
    
    print("Done!")

if __name__ == '__main__':
    main()
